### ISSUE TITLE
TODO list for 0.1 release

### ISSUE THREAD

**Issue by wilkgr76** [wilkgr76/cautious-robot#1]
# For 0.1:
- [ ] Add character (a robot)
- [x] Add more textures
- [ ] Add freeplay mode
# For 0.2:
- [ ] Add career mode (i.e. with story, and saving)
- [ ] Better follow camera
- [ ] Sounds?
# For 0.3:
- [ ] Race mode (against AI)
- [ ] Vehicles?
